/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    services: Service;
    posts: Post;
    media: Media;
    inquiries: Inquiry;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Edit the headings, introductions and search descriptions for your main pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: 'home' | 'work' | 'services' | 'studio' | 'book' | 'privacy' | 'terms' | 'blog';
  title: string;
  intro: string;
  /**
   * Choose an image from Media or upload a new one. Clear this field to remove the image.
   */
  image?: (number | null) | Media;
  /**
   * Optional search title. Aim for about 50–60 characters; the site adds the Paertner name.
   */
  seoTitle?: string | null;
  /**
   * Describe this page in about 140–160 characters. Empty fields use the page content.
   */
  seoDescription?: string | null;
  /**
   * Optional image for link previews. A landscape image around 1200 × 630 works well.
   */
  seoImage?: (number | null) | Media;
  /**
   * Leave empty to use this page’s own URL.
   */
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploads are automatically converted to WebP, capped at 2400 px, and given thumbnail, card and hero sizes. Add meaningful alternative text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Draft your case study, add imagery, then publish when it is ready to share.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  descriptor: string;
  sector: string;
  year?: string | null;
  liveURL?: string | null;
  order?: number | null;
  featured?: boolean | null;
  /**
   * Show the concept disclosure. Disable only for verified client projects.
   */
  concept?: boolean | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  challenge: string;
  idea: string;
  execution: string;
  result: string;
  details?:
    | {
        eyebrow?: string | null;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose an image from Media or upload a new one. Clear this field to remove the image.
   */
  image?: (number | null) | Media;
  art?: ('portal' | 'attention' | 'creation') | null;
  tone?: ('stone' | 'lime' | 'blue' | 'dark' | 'pink' | 'sage') | null;
  screens?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional search title. Aim for about 50–60 characters; the site adds the Paertner name.
   */
  seoTitle?: string | null;
  /**
   * Describe this page in about 140–160 characters. Empty fields use the page content.
   */
  seoDescription?: string | null;
  /**
   * Optional image for link previews. A landscape image around 1200 × 630 works well.
   */
  seoImage?: (number | null) | Media;
  /**
   * Leave empty to use this page’s own URL.
   */
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage service copy, deliverables and images shown on your website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  short: string;
  intro: string;
  category: 'Marketing' | 'Creation';
  number?: string | null;
  deliverables?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  approach?: string | null;
  outcome?: string | null;
  art?: ('portal' | 'attention' | 'creation') | null;
  /**
   * Choose an image from Media or upload a new one. Clear this field to remove the image.
   */
  image?: (number | null) | Media;
  /**
   * Optional search title. Aim for about 50–60 characters; the site adds the Paertner name.
   */
  seoTitle?: string | null;
  /**
   * Describe this page in about 140–160 characters. Empty fields use the page content.
   */
  seoDescription?: string | null;
  /**
   * Optional image for link previews. A landscape image around 1200 × 630 works well.
   */
  seoImage?: (number | null) | Media;
  /**
   * Leave empty to use this page’s own URL.
   */
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Write articles as drafts, set their SEO metadata, and publish when ready. Published articles appear at /blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  author: string;
  publishedAt: string;
  /**
   * Choose an image from Media or upload a new one. Clear this field to remove the image.
   */
  image?: (number | null) | Media;
  /**
   * Separate paragraphs with a blank line. Use ## for section headings, - for list items, and [link text](/internal-path) for links to your services or contact form.
   */
  body: string;
  /**
   * Optional search title. Aim for about 50–60 characters; the site adds the Paertner name.
   */
  seoTitle?: string | null;
  /**
   * Describe this page in about 140–160 characters. Empty fields use the page content.
   */
  seoDescription?: string | null;
  /**
   * Optional image for link previews. A landscape image around 1200 × 630 works well.
   */
  seoImage?: (number | null) | Media;
  /**
   * Leave empty to use this page’s own URL.
   */
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Review new inquiries, then mark them contacted or closed as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  service?: string | null;
  message: string;
  status?: ('new' | 'contacted' | 'closed') | null;
  fingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Keep old website links working by pointing them to a new internal page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  intro?: T;
  image?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  descriptor?: T;
  sector?: T;
  year?: T;
  liveURL?: T;
  order?: T;
  featured?: T;
  concept?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  challenge?: T;
  idea?: T;
  execution?: T;
  result?: T;
  details?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  image?: T;
  art?: T;
  tone?: T;
  screens?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  short?: T;
  intro?: T;
  category?: T;
  number?: T;
  deliverables?:
    | T
    | {
        label?: T;
        id?: T;
      };
  approach?: T;
  outcome?: T;
  art?: T;
  image?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  author?: T;
  publishedAt?: T;
  image?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  service?: T;
  message?: T;
  status?: T;
  fingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  contentVersion?: number | null;
  methodTitle?: string | null;
  methodSteps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  principles?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  name: string;
  tagline?: string | null;
  heroTitle: string;
  heroDescription: string;
  introTitle?: string | null;
  introBody?: string | null;
  convergenceTitle?: string | null;
  convergenceBody?: string | null;
  workTitle?: string | null;
  workDescription?: string | null;
  studioTitle?: string | null;
  studioBody?: string | null;
  ctaTitle?: string | null;
  ctaBody?: string | null;
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  bookingURL?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  heroPoster?: (number | null) | Media;
  studioImage?: (number | null) | Media;
  socialImage?: (number | null) | Media;
  /**
   * Enable only after concept content, legal policies, contact details, and production configuration have been reviewed.
   */
  allowIndexing?: boolean | null;
  privacy?: string | null;
  terms?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  contentVersion?: T;
  methodTitle?: T;
  methodSteps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  principles?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  name?: T;
  tagline?: T;
  heroTitle?: T;
  heroDescription?: T;
  introTitle?: T;
  introBody?: T;
  convergenceTitle?: T;
  convergenceBody?: T;
  workTitle?: T;
  workDescription?: T;
  studioTitle?: T;
  studioBody?: T;
  ctaTitle?: T;
  ctaBody?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  email?: T;
  bookingURL?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heroPoster?: T;
  studioImage?: T;
  socialImage?: T;
  allowIndexing?: T;
  privacy?: T;
  terms?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}